kind: pipeline
name: default

steps:
- name: build
  image: node:latest
  commands:
    - npm install
    - npm run build

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: ctfl.space
    username: root
    key:
      from_secret: ssh-key
    target: /root/ruetueta-server
    source: dist/*
  when:
    branch:
    - master
    event:
    - push
